=== gnardin/soari/conf/liar/translatorconfiguration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.lti.pcs.usp.br/TranslatorConfiguration"
 xmlns:tc="http://www.lti.pcs.usp.br/TranslatorConfiguration">
 
 <xsd:annotation>
   <xsd:documentation xml:lang="en">
     Translator Configuration XML schema
   </xsd:documentation>
 </xsd:annotation>
 
 <xsd:element name="TranslatorConfiguration" type="tc:TranslatorConfigurationType"/>

 <xsd:complexType name="TranslatorConfigurationType">
   <xsd:sequence>
     <xsd:element name="id" type="xsd:string"/>
     <xsd:element name="urlMapperServer" type="xsd:string"/>
     <xsd:element name="ontNativeName" type="xsd:string"/>
     <xsd:element name="ontNativeVersion" type="xsd:int"/>
     <xsd:element name="ontInterchangeName" type="xsd:string"/>
     <xsd:element name="ontInterchangeVersion" type="xsd:int"/>
     <xsd:element name="mapperClientClass" type="xsd:string"/>
     <xsd:element name="internalLanguageName" type="xsd:string"/>
     <xsd:element name="internalLanguageClass" type="xsd:string"/>
     <xsd:element name="inputTranslationStrategyClass" type="xsd:string"/>
     <xsd:element name="outputTranslationStrategyClass" type="xsd:string"/>
     <xsd:element name="valueTransformationConcept" type="xsd:string"/>
     <xsd:element name="valueTransformationClass" type="xsd:string"/>
     <xsd:element name="reputationReasonerClass" type="xsd:string"/>
   </xsd:sequence>
 </xsd:complexType>
</xsd:schema>

=== gnardin/soari/conf/typology/translatorconfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:TranslatorConfiguration
	xmlns:tc="http://www.lti.pcs.usp.br/TranslatorConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lti.pcs.usp.br/TranslatorConfiguration translatorconfiguration.xsd">

	<id>typologyAgent</id>
	<urlMapperServer>http://localhost:8080/axis2/services/MapperServerWebService</urlMapperServer>
	<ontNativeName>TYPOLOGY</ontNativeName>
	<ontNativeVersion>1</ontNativeVersion>
	<ontInterchangeName>FORE</ontInterchangeName>
	<ontInterchangeVersion>1</ontInterchangeVersion>
	<mapperClientClass>otservices.translator.mapperserverclient.ws.MapperClientWebService</mapperClientClass>
	<internalLanguageName>SPARQL</internalLanguageName>
	<internalLanguageClass>otservices.translator.language.sparql.SPARQLFactory</internalLanguageClass>
	<inputTranslationStrategyClass>otservices.translator.strategy.impl.HeuristicStrategy</inputTranslationStrategyClass>
	<outputTranslationStrategyClass>otservices.translator.strategy.impl.ZeroInputNAll</outputTranslationStrategyClass>
	<valueTransformationConcept>ReputationValueByTypology</valueTransformationConcept>
	<valueTransformationClass>otservices.translator.valuetransformation.art.TypologyFOREValueTransformation</valueTransformationClass>
	<reputationReasonerClass>otservices.translator.reputationreasoner.impl.typologyofreputation.TypologyReputationReasoner</reputationReasonerClass>
</tc:TranslatorConfiguration>

=== gnardin/soari/conf/liar/translatorconfiguration.xml
<?xml version="1.0" encoding="utf-8"?>
<tc:TranslatorConfiguration
	xmlns:tc="http://www.lti.pcs.usp.br/TranslatorConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lti.pcs.usp.br/TranslatorConfiguration translatorconfiguration.xsd">

	<id>liarAgent</id>
	<urlMapperServer>http://localhost:8080/axis2/services/MapperServerWebService</urlMapperServer>
	<ontNativeName>LIAR</ontNativeName>
	<ontNativeVersion>1</ontNativeVersion>
	<ontInterchangeName>FORE</ontInterchangeName>
	<ontInterchangeVersion>1</ontInterchangeVersion>
	<mapperClientClass>otservices.translator.mapperserverclient.ws.MapperClientWebService</mapperClientClass>
	<internalLanguageName>SPARQL</internalLanguageName>
	<internalLanguageClass>otservices.translator.language.sparql.SPARQLFactory</internalLanguageClass>
	<inputTranslationStrategyClass>otservices.translator.strategy.impl.HeuristicStrategy</inputTranslationStrategyClass>
	<outputTranslationStrategyClass>otservices.translator.strategy.impl.ZeroInputNAll</outputTranslationStrategyClass>
	<valueTransformationConcept>ReputationValueByLiar</valueTransformationConcept>
	<valueTransformationClass>otservices.translator.valuetransformation.art.LIARFOREValueTransformation</valueTransformationClass>
	<reputationReasonerClass>otservices.translator.reputationreasoner.impl.liar.LIARReputationReasoner</reputationReasonerClass>
</tc:TranslatorConfiguration>

=== gnardin/soari/conf/repage/translatorconfiguration.xml
<?xml version="1.0" encoding="utf-8"?>
<tc:TranslatorConfiguration
	xmlns:tc="http://www.lti.pcs.usp.br/TranslatorConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lti.pcs.usp.br/TranslatorConfiguration translatorconfiguration.xsd">

	<id>repageAgent</id>
	<urlMapperServer>http://localhost:8080/axis2/services/MapperServerWebService</urlMapperServer>
	<ontNativeName>REPAGE</ontNativeName>
	<ontNativeVersion>1</ontNativeVersion>
	<ontInterchangeName>FORE</ontInterchangeName>
	<ontInterchangeVersion>1</ontInterchangeVersion>
	<mapperClientClass>otservices.translator.mapperserverclient.ws.MapperClientWebService</mapperClientClass>
	<internalLanguageName>SPARQL</internalLanguageName>
	<internalLanguageClass>otservices.translator.language.sparql.SPARQLFactory</internalLanguageClass>
	<inputTranslationStrategyClass>otservices.translator.strategy.impl.HeuristicStrategy</inputTranslationStrategyClass>
	<outputTranslationStrategyClass>otservices.translator.strategy.impl.ZeroInputNAll</outputTranslationStrategyClass>
	<valueTransformationConcept>ValueByRepage</valueTransformationConcept>
	<valueTransformationClass>otservices.translator.valuetransformation.art.RepageFOREValueTransformation</valueTransformationClass>
	<reputationReasonerClass>otservices.translator.reputationreasoner.impl.repage.RepageReputationReasoner</reputationReasonerClass>
</tc:TranslatorConfiguration>
